//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda
    {
        public int idProstituta { get; set; }
        public int idQuarto { get; set; }
        public System.TimeSpan horaInicio { get; set; }
        public System.TimeSpan horaFim { get; set; }
    
        public virtual prostituta prostituta { get; set; }
        public virtual quarto quarto { get; set; }
    }
}
