//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BordelRussoEntities : DbContext
    {
        public BordelRussoEntities()
            : base("name=BordelRussoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agenda> agenda { get; set; }
        public virtual DbSet<bebida> bebida { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<prostituta> prostituta { get; set; }
        public virtual DbSet<quarto> quarto { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<tipoBebida> tipoBebida { get; set; }
        public virtual DbSet<tipoEspecialiade> tipoEspecialiade { get; set; }
        public virtual DbSet<tipoQuarto> tipoQuarto { get; set; }
        public virtual DbSet<venda> venda { get; set; }
    }
}
