//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class prostituta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prostituta()
        {
            this.agenda = new HashSet<agenda>();
        }
    
        public int idProstituta { get; set; }
        public double valor { get; set; }
        public int idTipoEspecialidade { get; set; }
        public Nullable<int> idSexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agenda { get; set; }
        public virtual tipoEspecialiade tipoEspecialiade { get; set; }
        public virtual sexo sexo { get; set; }
    }
}
