//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class quarto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quarto()
        {
            this.agenda = new HashSet<agenda>();
        }
    
        public int idQuarto { get; set; }
        public int numero { get; set; }
        public int idTipoQuarto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agenda> agenda { get; set; }
        public virtual tipoQuarto tipoQuarto { get; set; }
    }
}
