//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        public int idCliete { get; set; }
        public int idBebida { get; set; }
    
        public virtual bebida bebida { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
